### ISSUE TITLE
imagenet_and_broden_fetcher.py only able to fetch texture concepts

### ISSUE THREAD

**Issue by pmmitche** [tensorflow/tcav#101]
I'm modifying the download_and_make_datasets.py file to look at other concepts for Zebra TCAV, and when I try to change the concepts to color, or object, or other things, the broden fetcher tells me that no images were available. I noticed the imagenet_and_broden_fetcher.py only has a `download_texture_to_working_folder` function, and doesn't look like it supports fetching other concepts. I was wondering if this was the case and I would need to implement that myself, or if there is an established way in the open source code to fetch non-texture-based concepts like 'black-c' (a color concept)? Any help would be appreciated, thank you!

**Comment by jameswex** [comment]
It looks like that file was only used to create texture concepts from broaden. As you noticed, I think you could create a similar function to `download_texture_to_working_folder` to have it fetch color-based concepts. https://github.com/tensorflow/tcav/blob/master/tcav/tcav_examples/image_models/imagenet/imagenet_and_broden_fetcher.py#L220 shows that the current logic ignores any color-related images when looking for texture images.

@BeenKim what process did you go through to create color-based concepts from datasets? Was it from broaden?

**Comment by BeenKim** [comment]
Color-based concept: we simply created a tensor (3D for RGB) and filled in the right channel for each color with some added noise. For example, for red color concept image, you make an empty tensor, then only fill in R channel with full value (whatever your network expects) with some uniform noise! Make sure you visualize this made-up image to ensure the noise level is appropriate (ig you would expect to get varying shades of red).
