### ISSUE TITLE
requirement.txt file has a mistake

### ISSUE THREAD

**Issue by lothus** [tensorflow/tcav#104]
Numpy in the requirements text should be numpy==1.19.2

**Comment by jameswex** [comment]
Thanks for the report. What happens with the current setting of 1.16.0?

**Comment by lothus** [comment]
It complains that the requirements for Tensorflow 2.4 is numpy 1.19.2 or greater when doing the pip install -r requirements.txt . I have tested on my docker container and windows box and it works well with switching to numpy==1.19.2

**Comment by jameswex** [comment]
Thanks @lothus
