### ISSUE TITLE
No module found with name 'cav'

### ISSUE THREAD

**Issue by asghar3166** [tensorflow/tcav#23]
How do I install this module? I've tried multiple common commands that I am aware of. 

ModuleNotFoundError: No module named 'cav'

Following commands I tried:
pip install cav
conda install cav

**Comment by lightnarcissus** [comment]
I do not believe "cav" is a pip or an Anaconda package. You'll have to run the scripts and or Jupyter notebook that can import directly from "cav.py" file that is locally accessible.
Hope that makes sense!

**Comment by BeenKim** [comment]
lightnarcissus is right! cav class is just one of the file. If your question is if you can install TCAV on pip - that's a good idea, we'll look into that.
