### ISSUE TITLE
Significance testing for Relative TCAV

### ISSUE THREAD

**Issue by Ylja** [tensorflow/tcav#25]
I am currently trying to implement significance testing for relative CAVs. Lets says that, following the paper, I would like to train the CAV for 'striped', relative to 'dotted' and 'meshed'. As I understand this is trained by taking positive example set P_striped and negative set N := {P_dotted, P_meshed}. In the 'vanilla' CAV setting (concept set vs random set) we can do significance testing by taking N to be a random set, perform multiple runs in which we calculate the CAV from a new random set and perform a t-test on the mean TCAV score of these runs. However in the relative TCAV setting, to my understanding there is no varying random set and we can thus not perform multiple CAV calculations, which means there is no mean mean to use in a t-test.

In 4.2.1 and figure 4 you discuss relative TCAV results for different classes in InceptionV1 and V3 in different layers. Here you omit CAVs when their TCAV score does not significantly differ from 0.5. How can this be calculated? What Am I missing?

**Comment by BeenKim** [comment]
Sorry for the delay - I didn't know github would not notify me on this!

relative CAVs - you can still create many CAVs by randomly removing examples from each set. :)

significant difference - no those figures are just the concepts & layers that passed the statistical testing! The sentence in the paper is a bit unclear (sorry) with the 0.5 statement, I was trying to say that TCAV score at random would be 0.5. Statistical testing is just comparing random CAVs to concept CAVs there is no pre-set value that we are comparing against.
