### ISSUE TITLE
Using resnet

### ISSUE THREAD

**Issue by youyeg** [tensorflow/tcav#26]
Hi,
I was having problem with using TCAV with resnet. Could you provide me with an example?

**Comment by Ylja** [comment]
Not sure if you still have this problem, but if you do:
 I was able to use TCAV with custom networks and might be able to help. Perhaps you can post a question here: https://datascience.stackexchange.com/ with what you tried and where you get stuck and me and the rest of the community can try and help out!
(if you do post a question please reference it here, so I know where to find it!)

**Comment by sverma88** [comment]
Hi @youyeg, were you able to run on ResNet?
I'm also struggling with the same, thanks.
