### ISSUE TITLE
Tensorflow, scikit and matplotlib versions

### ISSUE THREAD

**Issue by aaossa** [tensorflow/tcav#28]
Hi, is there any documentation about which Tensorflow, matplotlib and scikit version were used? I sugged creating a `requirements.txt` file with the output of `pip freeze` to use the right version while running the files.

**Comment by BeenKim** [comment]
good idea (i'll get to it later)! This is not a complete set, but TCAV should work with tensorflow (1.13.1), matplotlib (2.2.4), and scikit-learn (0.20.0)

**Comment by BeenKim** [comment]
This has not been included in the requirements.txt . Thank you for this idea!
