### ISSUE TITLE
Question about non-image data

### ISSUE THREAD

**Issue by amjass12** [tensorflow/tcav#43]
Hi all, I came across tcav ands found this method really interesting! Before I dive in to this however, there are a few questions I have and would really appreciate any advice and clarification about this method. 

I am linking an issue here that I think is relevant to my use-case but i dont think fully answers my questions:

https://github.com/tensorflow/tcav/issues/35

I too am using tabular data. it is genomic data that consists of many thousands of features which collectively define different organs, ages, genders etc... (binary problem, so for one sample, there will be multiple labels (organ, gender, age etc)... 

I have built a simple sequential model which actually performs well in terms of its accuracy to different labels. However, what i would like to understand is which features define certain classes as well as which features might be shared across different samples by accessing hidden layers. 

I guess the question here is, is tcav a good use case for this sort of model? is it 'backwards' compatible? and what i mean by this is:

if i define labels such as gender.. if a true pattern is identified by the model, can tcav also tell me which features it found to be a defining factor for being  a male or female? in other words, even if it can tell me that stripes define a zebra, can i access also which pixels make up stripes?

or are values such as shap values a better way of doing this sort of analysis?

thank you!

**Comment by jameswex** [comment]
For the type of analysis you describe, shap values or path integrated gradients are probably better tools. TCAV by itself doesn't map those concepts (that you define through example images) back to pixels in the input images (or features in the input data).

**Comment by amjass12** [comment]
Hi @jameswex , 

Thank you very much for your answer and for clarifying! much appreciated.

**Comment by BeenKim** [comment]
If your label (e.g., gender) isn't your class label, then you can also do SHAP or PIG on **the gender CAV** down to pixel/feature space. If it is your class label, then straight up SHAP may work.
