### ISSUE TITLE
Folder name random500 seems to be hardcoded

### ISSUE THREAD

**Issue by thomaskeck** [tensorflow/tcav#5]
I encountered a minor problem while using tcav.
The folder name for the random examples seems to be hard-coded in utils.py, but the public interface to TCAV looks like the user can choose an arbitrary name.
https://github.com/tensorflow/tcav/blob/35e60bdc1716500eed16526cbe03131b096c10ac/utils.py#L82

**Comment by BeenKim** [comment]
Yes, this is true. I should add this to the tutorial ipynb. We will update this to be custom named (or at least not something too random like random500) in our next refactoring (or you are welcome to submit a PR). 
Thank you for catching this.
