### ISSUE TITLE
Can we extend the concept vectors to sequential data(LSTM, GRU)

### ISSUE THREAD

**Issue by MaharshiYeluri01** [tensorflow/tcav#50]
We have some medical domain vocabulary which contains a list of 500 unique events, we are using the GRU model to predict what might happen in the future, and while doing so we are looking for some explanation about what event is changing the model activations more, so how can we extend  TCAV to GRU or LSTM models
Thanks

**Comment by jameswex** [comment]
TCAV is useful when you want to determine how much effect a concept has on a prediction, where a concept is defined by a set of examples which contain the concept (like picking a bunch of images with stripes for the stripes concept, or a bunch of sentences about sports for a sports concept). If that is the type of analysis you want to do, TCAV can work with sequential models. You just need to do create the model wrapper and activation generator wrapper for your specific model. There is nothing about GRU or LSTM models that should stop you from using the library.

**Comment by yshvrdhn** [comment]
Hi can it be used similarly for segmentation networks ?

**Comment by BeenKim** [comment]
Hi all, 

Yes, just repeating what James said above - TCAV has been used for LSTM at Google - as long as you have a constant sized bottleneck (meaning that you have at least one embedding layer where it will always return a size N embedding regardless of your input size. This is probably only relevant for language models where some models change their embedding size  depending on the length of the input sentence). 

Re segmentation network  - same story. :)
