### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by justcho5** [tensorflow/tcav#56]
TCAV library -- there's a problem when importing in utils.py. Particularly the line when importing the results_pb2 module. I fixed it by changing "from tcav_results.results_pb2..." to "...tcav.tcav_results_pb2...".

Also there is an incompatibility with tf 2.0. I've tried by replacing tf. with tf.compat.v1. However, I then ran into a decode error, which i opened another issue on.

In addition, i get this error:
File "./tcav/tcav/model.py", line 318, in import_graph
graph_def = tf.compat.v1.GraphDef.FromString(tf.compat.v1.gfile.Open(saved_path, 'rb').read())
google.protobuf.message.DecodeError: Error parsing message

Do you know how I could resolve this problem? Thank you

**Comment by jameswex** [comment]
@BeenKim @sherryy have either of you seen these issues before?

**Comment by sherryy** [comment]
I have seen this error when the graph is in the wrong format. Is your graph
ends in '.pb'? Make sure your graph is saved using something like
"tf.io.write_graph(output_graph_def, frozen_graph_dir, 'graph.pb',
as_text=False)" if you are loading it using
"tf.GraphDef.FromString(tf.gfile.Open(saved_path,
'rb').read())" as on line 318 of model.py.

**Comment by BeenKim** [comment]
Thanks Sherry! @justcho5 please feel free to reopen this issue if it wasn't resolved.

**Comment by vasanth4224** [comment]
I have also the same problem, anyone can give some solutions to this problem.
This is my code...
detection_graph=tf.Graph()
with detection_graph.as_default():
  od_graph_def=tf.GraphDef()
  with tf.gfile.GFile(PATH_TO_FROZEN_GRAPH, 'rb') as fid:
    serialized_graph=fid.read()
    od_graph_def.ParseFromString(serialized_graph)
    # od_graph_def.ParseFromString('saved_model.pb')
    tf.import_graph_def(od_graph_def, name='')
    # tf.import_graph_def(od_graph_def, name='prefix')



Error line:
Traceback (most recent call last):
  File "D:/TensorFlow-2/raccoon_dataset-master/object_detection_testing_yolov4.py", line 54, in <module>
    od_graph_def.ParseFromString(serialized_graph)
google.protobuf.message.DecodeError: Error parsing message
