### ISSUE TITLE
question regarding model wrappers (xception model)

### ISSUE THREAD

**Issue by justcho5** [tensorflow/tcav#57]
Hi I have a imagenet-pretrained xception network trained on histology images. I would like to be able to use tcav with this model; however, I'm unsure of how to determine the bottleneck layers that tcav asks for. 1) am i able to use this model for tcav and 2) do you have any suggestions on how to get the bottleneck tensors? I can get all the tensors for the network with graph.get_operations but I'm not sure if any or which of those are relevant. 

Thank you for your help!

**Comment by jameswex** [comment]
@BeenKim @sherryy what is the best way to bottleneck tensors for use with TCAV from a new model?

**Comment by sherryy** [comment]
You can either look at the code that built the model to see what bottleneck names are used, or you can look at the graph in pbtxt format (either directly look at the file or load it to a graph visualizer) and find the node name you're interested in.

**Comment by BeenKim** [comment]
The bottleneck layers typically (not always!) has concat operation (so it is a layer that sort of 'collects' all the bottom layer's responses). You can perhaps look through the loaded graph, and go thru n.node.name (similar to what Sherry mentions above). 

Your question might also have to do with 'if I have many bottlenecks, how do I chose one?'  I recommend starting from the top layer (a layer closest to the prediction layer) and do the statistical testing (t-test, in the code) and go down one by one until you find one that passes the test. 

Feel free to reopen this issue if it hasn't been resolved!

**Comment by justcho5** [comment]
Thank you for the detailed answer! Which part of the code are you referencing for the t-test?

**Comment by BeenKim** [comment]
This part:
https://github.com/tensorflow/tcav/blob/1d0758713c3eaf404fdd8bf2bb914a76c4813c87/tcav/utils.py#L219

This will get printed as a result.
