### ISSUE TITLE
reference to previous issue about choosing bottleneck nodes

### ISSUE THREAD

**Issue by justcho5** [tensorflow/tcav#58]
Thank you for the detailed answer! Which part of the code are you referencing for the t-test?

This is my first time using the xception model and tcav so I'm not sure but it doesnt look like xception has concat operations. Also, I visualized the graph and it looks like many consecutive depthwise separable convolutions with residual connections in between so there isnt an obvious bottleneck layer like in googlenet or inceptionv3. Is there a specific definition for what the bottleneck layer should be? The only operation I see that collects bottom layer outputs is the "add" operation which are where the residual connection occur. Sorry for asking so many quesitons about this!

_
![image](https://user-images.githubusercontent.com/19522811/68504294-42c04400-022a-11ea-8953-1bffd27a2d7d.png)
______

The bottleneck layers typically (not always!) has concat operation (so it is a layer that sort of 'collects' all the bottom layer's responses). You can perhaps look through the loaded graph, and go thru n.node.name (similar to what Sherry mentions above). 

Your question might also have to do with 'if I have many bottlenecks, how do I chose one?'  I recommend starting from the top layer (a layer closest to the prediction layer) and do the statistical testing (t-test, in the code) and go down one by one until you find one that passes the test. 

Feel free to reopen this issue if it hasn't been resolved!

_Originally posted by @BeenKim in https://github.com/tensorflow/tcav/issues/57#issuecomment-551938183_

**Comment by BeenKim** [comment]
Good question and sorry for the delayed reply. Intuitively speaking, by bottleneck layer I'm referring to any layer where "all information is coming together". So in your case, it seems that you have skip connections, and perhaps the best candidate is after (each) skip connections (ie where the + sign is). I typically try to do the top layer first, so if I'm reading your diagram correction, I'd try "2048 dimensional vectors" first.
