### ISSUE TITLE
Inceptionv3 pb file?

### ISSUE THREAD

**Issue by justcho5** [tensorflow/tcav#59]
I know that the googlenet pb file is uploaded, but could you also release the inceptionv3 pb file that was used? I would like to compare the results with the inception v3 model I have from keras. There are some differences with parsing from the pb files and since I was unable to use the import graph function (FromString) provided in PublicImageModelWrapper, I modified it to be able to parse the protobuf file (ParseFromString) I got from the pretrained keras model. I don't know why the FromString function in the class method does not work for my model but it would be good to compare...The names of the tensors are also slightly different so I'm not sure if the correct tensors were used for the endpoints dictionary.

**Comment by kavi2015** [comment]
@justcho5, I also have the same question/request :).  And I must be missing it, but where did you find the inceptionV3 pb file?  Is it part of the gitHub repo (if so, which directly is it available under?), or is it available elsewhere?  Thank you!

**Comment by BeenKim** [comment]
Hi all, 

Unfortunately we were not able to get permission to open source this particular model. But this question seems to be more on tensorflow side - no matter what model you use, TCAV requires the exact tensor name (that endpoints dictionary takes). This can be done by parsing the graph (which sounds like you are using). Have you tried what's suggested here? https://stackoverflow.com/questions/35336648/list-of-tensor-names-in-graph-in-tensorflow

feel free to reopen if your model still doesn't work w/ tensor names.
