### ISSUE TITLE
Unable to run the tests, program and notebook

### ISSUE THREAD

**Issue by akhilpandey95** [tensorflow/tcav#60]
Hey there,

I was trying  to use the code from the repository and i found that things were not working for me. Here are the things that are of concern to me :  
- `Run TCAV.ipynb` returns me an error saying `No module named tcav_results` despite installing tcav.
- `pip install -r requirements.txt` throws an error because you used a single `=` sign instead of `==`.
- `python -m tcav.cav_test` throws me an error saying `ModuleNotFoundError: No module named 'tcav_results' `

Useful information : 

- `python --version`
> Python 3.6.5

- `pip --version`
> pip 19.3.1

- `uname -a`
> Linux x1 4.15.0-70-generic #79~16.04.1-Ubuntu SMP Tue Nov 12 14:01:10 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jameswex** [comment]
I'll take a look this week. Thanks for pointing this out.

**Comment by jameswex** [comment]
To run the TCAV notebook and tests, 'pip install tcav'. also pip install tensorflow or tensorflow-gpu' depending on if you want to use your GPU with tensorflow. Then the notebook and UTs should work. You don't need to clone this repo or built it from source, just use the pip package. You won't need to use requirements.txt as the tcav pip package will install all deps, except tensorflow which you can also pip install.

But I have fixed the requirements.txt file as you pointed out.

Let me know if these steps work for you.

**Comment by akhilpandey95** [comment]
@jameswex  Since you are still using `Session`,  I am assuming this wouldn't work if I use `tf 2.0` ?

**Comment by ElegantLin** [comment]
@akhilpandey95 Did you solve the problem? I also met this problem.

**Comment by jameswex** [comment]
That is correct, TCAV has not yet been updated for TF2 but will be. I don't have a date for that change yet.

**Comment by ElegantLin** [comment]
Hi, @jameswex , Thanks for your reply. I still met this problem and the following is my `pip list`

```
ModuleNotFoundError: No module named 'tcav_results'
(tcav) dzl@gpuserver1:~/ace/tcav$ pip list
Package              Version
-------------------- -------------------
absl-py              0.9.0
astor                0.8.1
certifi              2019.11.28
cycler               0.10.0
gast                 0.2.2
google-pasta         0.1.8
grpcio               1.27.2
h5py                 2.10.0
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
kiwisolver           1.1.0
Markdown             3.2.1
matplotlib           2.2.4
numpy                1.17.0
opt-einsum           3.2.0
pandas               1.0.1
Pillow               6.2.0
pip                  20.0.2
protobuf             3.10.0
pydicom              1.3.0
pyparsing            2.4.6
python-dateutil      2.8.1
pytz                 2019.3
scikit-learn         0.20.3
scipy                1.2.1
setuptools           45.2.0.post20200210
six                  1.14.0
tcav                 0.2.1
tensorboard          1.15.0
tensorflow           1.15.2
tensorflow-estimator 1.15.1
termcolor            1.1.0
Werkzeug             1.0.0
wheel                0.34.2
wrapt                1.12.0
```

Do you know the reason? I just clone your repo and `pip install -r requirements.txt`. 

Thanks for your help.

**Comment by jameswex** [comment]
Hi @ElegantLin, thanks for the info.

I have a PR up for review that addresses your issue and makes a few more updates to clean up the code: #68

**Comment by ElegantLin** [comment]
Hi, @jameswex . I have pulled the code of your PR and it works. Thanks a lot!

**Comment by jameswex** [comment]
Great! The PR has been merged so I will close this issue.
