### ISSUE TITLE
Sorting images with CAVs 

### ISSUE THREAD

**Issue by jisoolee0123** [tensorflow/tcav#69]
Hi all. Thanks for sharing the code. I've been trying to reproduce the results of the paper, and I have a question about **Section 4.1.1. Sorting images with CAVs** saying that 

> we can compute cosine similarity between a set of pictures of interest to the CAV to sort the pictures. 

Does it mean that for each picture in the set, we compute the cosine similarity between CAV and the **activation** of the picture and then sort the pictures by the measured similarity? 

I'd appreciate it if you give me some clarification. Thanks!

**Comment by jameswex** [comment]
You are correct. We take a trained CAV for some layer of the model, and then the activation of images at the same layer, and compute cosine similarity between activations and CAV, in order to rank/sort those pictures.

**Comment by jisoolee0123** [comment]
Thanks for the quick reply!

**Comment by cnmckee** [comment]
Does it make sense to take the average of the cosine similarities between the activations and all of the different CAVs from the random groups, for robustness? Worried about the possibility of spurious results from using one CAV generated from a single random set.
