### ISSUE TITLE
Object Concepts

### ISSUE THREAD

**Issue by cnmckee** [tensorflow/tcav#79]
Hello, I am trying to use an object concept to sort images. I cannot find mention of the format of input for object CAVs in the repo or paper. The Broden daatset provides specific masks for objects of interest appearing in the dataset. In the paper, when using an object concept, did you mask out the regions of images corresponding to the object of interest, zero out the background, and use the resulting images for the concept dataset? Or crop the image based on the mask to only include the object? Or assemble a completely new dataset, separate from Broden, consisting of images of the object concept? Or something else completely?

**Comment by BeenKim** [comment]
Hello, 

we did not crop anything or mask out - just used the images as they are (except we scale the image so that the network doesn't freak out). We just checked in this notebook to download broaden dataset in a local folder so that you can see how exactly we processed it: https://github.com/tensorflow/tcav/tree/master/tcav/tcav_examples/image_models/imagenet

Hope this helps,
Been

**Comment by cnmckee** [comment]
Okay, thanks for the reply! To clarify- if for example I wanted the concept of interest to be a "refrigerator", I would just take all Broden images with the refrigerator class present, even if the refrigerator is a relatively small part of the image, and use the whole image (after resizing) as input? Are you not then introducing many confounding variables?
I ask because in the directory you linked above, the code can only be used to extract patterns from the Broden dataset (download_texture_to_working_folder()), which appear as entire images of that pattern. This is very different than how the objects appear (in context).

**Comment by BeenKim** [comment]
Yes correct. If all your fridges are next to a sink, then yes, there might be some confounding effect. But we thought imposing having masks for every image is a harder constraint. If you do have bounding box, then you could use it for sure. 
what do you mean by "This is very different than how the objects appear (in context)."?
