### ISSUE TITLE
AttributeError: 'KerasModelWrapper' object has no attribute 'get_image_shape'

### ISSUE THREAD

**Issue by anandaman43** [tensorflow/tcav#81]
I finetuned Mobilenetv2 architecture with few dense layers added to it.When I tried to run KerasModelWrapper with my models.h5 file, it's throwing error - 'KerasModelWrapper' object has no attribute 'get_image_shape'.

**Comment by zhekz** [comment]
Hi! Were you able to solve the problem?
I am having the same issue

**Comment by jameswex** [comment]
KerasModelWrapper doesn't have get_image_shape already defined on it it seems (https://github.com/tensorflow/tcav/blob/master/tcav/model.py#L235 is where it is defined for a different model wrapper). Try creating a new model wrapper class that inherits from KerasModelWrapper and implements the get_image_shape method for your specific images.

**Comment by zhekz** [comment]
Hi @jameswex ,

Thank you! It helped! I just added that function to _KerasModelWrapper_ function and it worked as well.
