### ISSUE TITLE
Specifications of 500 random experiments

### ISSUE THREAD

**Issue by shan2312** [tensorflow/tcav#85]
Hi,
Can you please share the specifications of TCAV hyposthesis testing ?. Some information like number of workers used, type of GPU and run time will be really helpful.

**Comment by also-a-brain-known-as-ralph** [comment]
Hey Shan.

On the paper, we used 500 random experiments, with around 200 examples per concept.

As for the run time information, this [colab](https://github.com/tensorflow/tcav/blob/master/Run_TCAV_on_colab.ipynb) provides some good starting points. The public interpretation of TCAV runs on the cpu and does not require GPU usage or complex distributed data pipelines

**Comment by BeenKim** [comment]
Closing per also-a-brain-known-as-ralph answers.
