### ISSUE TITLE
is tcav better when compared with LIME,SHAP

### ISSUE THREAD

**Issue by dsvrsec** [tensorflow/tcav#90]
is tcav better when compared with LIME,SHAP

**Comment by jameswex** [comment]
TCAV is fundamentally different than feature-based methods such as LIME and SHAP. LIME and SHAP attribute predictions back to individual input features from an input example (i.e. how much did the value in the "age" field affect the prediction of "yes" for some model). TCAV allows people to create "concepts" that are not defined by single feature values, but by sets of input examples that all represent some human-understandable "concept". And then the sensitivity of the model to that concept is calculated.
