### ISSUE TITLE
Choose random images

### ISSUE THREAD

**Issue by LordDoggo** [tensorflow/tcav#95]
hi,

if i test cavs on human face detection, what random images should i use?
e.g. if my concept is women, do i need random images of faces without women, to train the linear classifier properly?
or should i take completely random images?

**Comment by jameswex** [comment]
You can train a standard CAV by having those concept images versus a totally random sample, or you can train a relative CAV by having those concept images versus  a set of images of another class, such as male faces. Both approaches have advantages and it might be worth trying both out to see what results you get. It often depends on what images you expect your classifier to see and what exactly you want to accomplish through your CAV.

**Comment by LordDoggo** [comment]
Thanks, i tried both and still getting confusing results (male people getting higher tcav-scores for women, female for male, ...). Not sure what i'm doing wrong.
this is the network i'm using https://github.com/rcmalli/keras-vggface/blob/master/visualize/resnet50.png are the add layers the right bottleneck layers?

**Comment by LordDoggo** [comment]
Found "relative tcav option" and read the paper again, answered my questions. Thanks
